version: '3.8'
volumes:
  db-store:
    driver: local
services:
  db:
    image: postgres:15.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${POSTGRES_TZ}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} || exit 1
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
  api:
    build: .
    tty: true
    ports:
      - ${API_PORT}:4000
    env_file:
      - .env
    volumes:
      - .:/app:cached
    depends_on:
      db:
        condition: service_healthy


