// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/liac-inc/gqlgen-template/src/graph/resolver"
	"github.com/liac-inc/gqlgen-template/src/repository"
	"github.com/liac-inc/gqlgen-template/src/service"
)

// Injectors from wire.go:

func InitializeResolver(db *sql.DB) *resolver.Resolver {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	resolverResolver := resolver.NewResolver(userService)
	return resolverResolver
}

// wire.go:

var userSet = wire.NewSet(service.NewUserService, repository.NewUserRepository, wire.Bind(new(service.IUserService), new(*service.UserService)), wire.Bind(new(repository.IUserRepository), new(*repository.UserRepository)))
